### ISSUE TITLE
Marked no longer supports objects with multiple properties to be set as prop values

### ISSUE THREAD

**Issue by bryandowning** [storybookjs/marksy#63]
...and in general, they do not support JSX syntax.

See this issue for more detail: https://github.com/markedjs/marked/issues/1194

This is obviously a huge bummer, but it might be worth hardcoding the version number of the marked dependency to `0.3.12` to avoid getting a later version that breaks.

**Comment by mmmaaatttttt** [comment]
Hey @bryandowning! I'm dealing with this issue as well. Have you checked out MDX? https://github.com/mdx-js/mdx#mdx-syntax I'm thinking I may need to transition away from marksy, but was curious to see if you've found any other solutions.

**Comment by bryandowning** [comment]
Hey, unfortunately I have not been able to come up with another solution yet. Thanks for sharing the MDX link! Definitely looks compelling!

Looks like it doesn't have much traction, but seeing Tim and Guillermo from ZEIT listed as authors makes me happy (I'm using next.js for my site).

**Comment by bryandowning** [comment]
@mmmaaatttttt Looks like MDX won't work for string content coming from an API, because it only works at build time — not runtime.

See this thread: https://github.com/mdx-js/mdx/issues/126#issuecomment-389073920
