### ISSUE TITLE
Rendering custom components doesn't work

### ISSUE THREAD

**Issue by kitze** [storybookjs/marksy#97]
I've been trying to figure this out for probably 3 solid hours, but either I'm missing something obvious or there is a bug. You can check it out in [this sandbox](https://codesandbox.io/s/silly-microservice-yryy0?file=/src/Preview.tsx).

**Comment by yannbf** [comment]
Hey @kitze, indeed there seems to be something weird in version 8, could be related to dependency updates.

If you try earlier versions like 7.0.1, custom components do work. 
I've setup [a playground](https://codesandbox.io/s/marksy-playground-zigv4) with examples that work if that helps:
![image](https://user-images.githubusercontent.com/1671563/91100133-eb7a4b80-e664-11ea-869a-2dde55ab63f6.png)

Other than that we can check if @christianalfoni or @ndelangen have any clues, maybe the way to use the lib has changed somehow? Let me know if I can help somehow :)

**Comment by kitze** [comment]
Thanks @yannbf, I'll downgrade for now

**Comment by ndelangen** [comment]
Storybook doesn't really use this lib anymore, we do the markdown / jsx transformation in webpack loaders now.

**Comment by kitze** [comment]
If anyone stumbles upon the same issue: I moved to https://github.com/probablyup/markdown-to-jsx
